/**
 * RideX shared mobile asset registry.
 *
 * Keep asset require() declarations in this module so the Customer, Driver and
 * Admin mobile apps use one canonical asset map. Do not use archive/reference assets here.
 */

export const CUSTOMER_ASSETS = {
  logo: require("../../customer/assets/brand/ridex_logo.png"),
  hero: require("../../customer/assets/ridex-hero.png"),
  eRickshaw: require("../../customer/assets/e-rickshaw.png"),
  pickupTruck: require("../../customer/assets/pickup-truck.png"),
  icons: {
    menu: require("../../customer/assets/icons/01_menu.png"),
    back: require("../../customer/assets/icons/01_back.png"),
    close: require("../../customer/assets/icons/01_close.png"),
    next: require("../../customer/assets/icons/01_next.png"),
    home: require("../../customer/assets/icons/01_home.png"),
    history: require("../../customer/assets/icons/01_history.png"),
    ride: require("../../customer/assets/icons/01_ride.png"),
    search: require("../../customer/assets/icons/01_search.png"),
    map: require("../../customer/assets/icons/01_target.png"),
    recenter: require("../../customer/assets/icons/01_recenter.png"),
    layers: require("../../customer/assets/icons/01_map_layers.png"),
    notification: require("../../customer/assets/icons/01_notification.png"),
    wallet: require("../../customer/assets/icons/01_wallet.png"),
    settings: require("../../customer/assets/icons/01_settings.png"),
    pickup: require("../../customer/assets/icons/01_pickup_location.png"),
    profile: require("../../customer/assets/icons/01_profile.png"),
    passengers: require("../../customer/assets/icons/02_passengers.png"),
    shared: require("../../customer/assets/icons/02_shared_ride.png"),
    parcel: require("../../customer/assets/icons/02_parcel.png"),
    parcelSet: require("../../customer/assets/icons/02_parcel_set.png"),
    truck: require("../../customer/assets/icons/02_pickup_truck_goods.png"),
    promo: require("../../customer/assets/icons/02_promo.png"),
    rating: require("../../customer/assets/icons/02_rating.png"),
    rebook: require("../../customer/assets/icons/02_rebook.png"),
    receipt: require("../../customer/assets/icons/02_receipt.png"),
    route: require("../../customer/assets/icons/02_route.png"),
    schedule: require("../../customer/assets/icons/02_schedule.png"),
    clock: require("../../customer/assets/icons/02_clock.png"),
    cash: require("../../customer/assets/icons/02_cash.png"),
    card: require("../../customer/assets/icons/02_card.png"),
    upi: require("../../customer/assets/icons/02_upi_wallet.png"),
    support: require("../../customer/assets/icons/02_support.png"),
    callback: require("../../customer/assets/icons/03_callback.png"),
    camera: require("../../customer/assets/icons/03_camera.png"),
    email: require("../../customer/assets/icons/03_email.png"),
    emergencyCall: require("../../customer/assets/icons/03_emergency_call.png"),
    emergencyContact: require("../../customer/assets/icons/03_emergency_contact.png"),
    faq: require("../../customer/assets/icons/03_faq.png"),
    gallery: require("../../customer/assets/icons/03_gallery.png"),
    liveChat: require("../../customer/assets/icons/03_live_chat.png"),
    liveLocation: require("../../customer/assets/icons/03_live_location.png"),
    report: require("../../customer/assets/icons/03_report_issue.png"),
    safety: require("../../customer/assets/icons/03_safety_shield.png"),
    security: require("../../customer/assets/icons/03_security_lock.png"),
    sos: require("../../customer/assets/icons/03_sos.png"),
    headset: require("../../customer/assets/icons/03_support_headset.png"),
    verified: require("../../customer/assets/icons/03_verified.png"),
    whatsapp: require("../../customer/assets/icons/03_whatsapp.png"),
    language: require("../../customer/assets/icons/04_language.png"),
    edit: require("../../customer/assets/icons/04_edit.png"),
    logout: require("../../customer/assets/icons/04_logout.png"),
    otp: require("../../customer/assets/icons/04_otp.png"),
    paymentCard: require("../../customer/assets/icons/04_payment_card.png"),
    phone: require("../../customer/assets/icons/04_phone.png"),
    profileCamera: require("../../customer/assets/icons/04_profile_camera.png"),
    profileFallback: require("../../customer/assets/icons/04_profile_fallback.png"),
    rewards: require("../../customer/assets/icons/04_rewards.png"),
    settingsProfile: require("../../customer/assets/icons/04_settings_profile.png"),
    wallet2: require("../../customer/assets/icons/04_wallet.png"),
    homeSaved: require("../../customer/assets/icons/04_home_saved.png"),
    workSaved: require("../../customer/assets/icons/04_work_saved.png"),
    rupee: require("../../customer/assets/icons/02_cash.png"),
    chevron_down: require("../../customer/assets/png/64/chevron_down.png"),
    check: require("../../customer/assets/png/64/check.png"),
  },
} as const;

export const DRIVER_ASSETS = {
  logo: require("../../driver/assets/brand/ridex_logo.png"),
  hero: require("../../driver/assets/driver-hero.png"),
  avatar: require("../../driver/assets/driver-avatar.png"),
  vehicle: require("../../driver/assets/driver-rickshaw.png"),
  icons: {
    menu: require("../../driver/assets/png/64/menu.png"),
    back: require("../../driver/assets/png/64/back.png"),
    home: require("../../driver/assets/png/64/home.png"),
    rides: require("../../driver/assets/png/64/rides.png"),
    earnings: require("../../driver/assets/png/64/earnings.png"),
    messages: require("../../driver/assets/png/64/messages.png"),
    profile: require("../../driver/assets/png/64/profile.png"),
    notification: require("../../driver/assets/png/64/bell.png"),
    support: require("../../driver/assets/png/64/support.png"),
    wallet: require("../../driver/assets/png/64/wallet.png"),
    settings: require("../../driver/assets/png/64/settings.png"),
    location: require("../../driver/assets/png/64/location_pin.png"),
    locationRed: require("../../driver/assets/png/64/location_pin_red.png"),
    pickup: require("../../driver/assets/png/64/location_pin.png"),
    drop: require("../../driver/assets/png/64/location_pin_red.png"),
    chevron_right: require("../../driver/assets/png/64/chevron_right.png"),
    navigate: require("../../driver/assets/png/64/navigate.png"),
    target: require("../../driver/assets/png/64/target.png"),
    layers: require("../../driver/assets/png/64/layers.png"),
    rupee: require("../../driver/assets/png/64/money.png"),
    clock: require("../../driver/assets/png/64/clock.png"),
    passengers: require("../../driver/assets/png/64/passenger_service.png"),
    goods: require("../../driver/assets/png/64/goods.png"),
    check: require("../../driver/assets/png/64/check.png"),
    close: require("../../driver/assets/png/64/close.png"),
    sos: require("../../driver/assets/png/64/sos.png"),
    shield: require("../../driver/assets/png/64/shield.png"),
    chat: require("../../driver/assets/png/64/chat.png"),
    phone: require("../../driver/assets/png/64/phone.png"),
    vehicle: require("../../driver/assets/png/64/vehicle.png"),
    both: require("../../driver/assets/png/64/both_services.png"),
    passenger: require("../../driver/assets/png/64/passenger_service.png"),
    parcel: require("../../driver/assets/png/64/parcel.png"),
    edit: require("../../driver/assets/png/64/edit.png"),
    document: require("../../driver/assets/png/64/document.png"),
    kyc: require("../../driver/assets/png/64/kyc.png"),
    calendar: require("../../driver/assets/png/64/calendar.png"),
    bank: require("../../driver/assets/png/64/bank.png"),
    rating: require("../../driver/assets/png/64/star.png"),
    online: require("../../driver/assets/png/64/online.png"),
    alert: require("../../driver/assets/png/64/warning.png"),
  },
} as const;

export const ADMIN_MOBILE_ASSETS = {
  logo: require("../../admin/assets/brand/ridex_admin_logo.png"),
  icons: {
    drivers: require("../../admin/assets/icons/drivers.png"),
    kyc: require("../../admin/assets/icons/kyc.png"),
    bookings: require("../../admin/assets/icons/bookings.png"),
    payments: require("../../admin/assets/icons/payments.png"),
    support: require("../../admin/assets/icons/support.png"),
    back: require("../../admin/assets/icons/back.png"),
    search: require("../../admin/assets/icons/search.png"),
    refresh: require("../../admin/assets/icons/refresh.png"),
  },
} as const;

export const RIDEX_MOBILE_ASSETS = { customer: CUSTOMER_ASSETS, driver: DRIVER_ASSETS, admin: ADMIN_MOBILE_ASSETS } as const;
