import { Router, Request, Response } from "express";
import { prisma } from "../lib/prisma";
import { AuditAction, AdminApprovalStatus } from "@prisma/client";
import { ensureEnvironmentControl, getEnvironmentState } from "../services/platform";

const router = Router();

async function superAdmin(req: Request, res: Response) {
  const userId = String(req.auth?.userId || req.headers["x-admin-user-id"] || "").trim();
  if (!userId) { res.status(401).json({ success: false, message: "Admin authentication required" }); return null; }
  const admin = await prisma.adminUser.findUnique({ where: { userId }, include: { role: true } });
  if (!admin || admin.approvalStatus !== AdminApprovalStatus.APPROVED || String(admin.role.name).toUpperCase() !== "SUPER_ADMIN") {
    res.status(403).json({ success: false, message: "Super Admin access required" }); return null;
  }
  return admin;
}

async function audit(adminId: string, req: Request, action: AuditAction, module: string, entityId?: string, beforeData?: unknown, afterData?: unknown) {
  await prisma.auditLog.create({ data: { adminId, action, module, entityType: "PLATFORM", entityId, beforeData: beforeData as any, afterData: afterData as any, ipAddress: req.ip, userAgent: String(req.headers["user-agent"] || "") } });
}

router.get("/state", async (req, res) => { try { if (!(await superAdmin(req, res))) return; return res.json({ success: true, ...(await getEnvironmentState()) }); } catch (e) { return res.status(500).json({ success:false,message:e instanceof Error?e.message:String(e)}); } });

router.put("/environment", async (req, res) => {
  try {
    const admin = await superAdmin(req, res); if (!admin) return;
    const environment = String(req.body?.environment || "").toUpperCase();
    if (environment !== "TEST" && environment !== "LIVE") return res.status(400).json({success:false,message:"environment must be TEST or LIVE"});
    if (environment === "LIVE") return res.status(409).json({success:false,message:"LIVE can only be entered by promoting a tested APPROVED project release"});
    const before = await ensureEnvironmentControl();
    const control = await prisma.environmentControl.update({ where:{key:"RIDEX_PRIMARY_ENVIRONMENT"}, data:{activeEnvironment:"TEST", deploymentStatus:"TESTING", updatedByAdminId:admin.id} });
    await audit(admin.id, req, AuditAction.CONFIG_CHANGE, "environment", control.id, before, control);
    return res.json({success:true,data:control});
  } catch(e){ return res.status(500).json({success:false,message:e instanceof Error?e.message:String(e)}); }
});

router.post("/testers", async (req,res)=>{ try { const admin=await superAdmin(req,res); if(!admin)return; const mobile=String(req.body?.mobile||"").replace(/\D/g,""); if(!/^\d{10}$/.test(mobile))return res.status(400).json({success:false,message:"Valid 10-digit mobile required"}); const tester=await prisma.approvedTester.upsert({where:{mobile},update:{active:true,revokedAt:null,approvedAt:new Date(),approvedBy:admin.id,label:req.body?.label?String(req.body.label):undefined},create:{mobile,label:req.body?.label?String(req.body.label):null,approvedBy:admin.id}}); await audit(admin.id,req,AuditAction.ADMIN_APPROVAL,"approved_testers",tester.id,undefined,tester); return res.json({success:true,data:tester}); } catch(e){return res.status(500).json({success:false,message:e instanceof Error?e.message:String(e)});} });
router.delete("/testers/:mobile", async(req,res)=>{ try{const admin=await superAdmin(req,res);if(!admin)return;const mobile=String(req.params.mobile).replace(/\D/g,"");const tester=await prisma.approvedTester.update({where:{mobile},data:{active:false,revokedAt:new Date()}});await audit(admin.id,req,AuditAction.UPDATE,"approved_testers",tester.id,undefined,tester);return res.json({success:true,data:tester});}catch(e){return res.status(500).json({success:false,message:e instanceof Error?e.message:String(e)});} });

router.post("/releases", async(req,res)=>{try{const admin=await superAdmin(req,res);if(!admin)return;const version=String(req.body?.version||"").trim();if(!version)return res.status(400).json({success:false,message:"version is required"});const release=await prisma.projectRelease.create({data:{version,sourceLabel:req.body?.sourceLabel?String(req.body.sourceLabel):null,checksum:req.body?.checksum?String(req.body.checksum):null,environment:"TEST",status:"UPLOADED",notes:req.body?.notes?String(req.body.notes):null}});await audit(admin.id,req,AuditAction.CREATE,"project_release",release.id,undefined,release);return res.json({success:true,data:release});}catch(e){return res.status(500).json({success:false,message:e instanceof Error?e.message:String(e)});} });
router.post("/releases/:id/test-start", async(req,res)=>{try{const admin=await superAdmin(req,res);if(!admin)return;const release=await prisma.projectRelease.update({where:{id:req.params.id},data:{environment:"TEST",status:"TESTING",testStartedAt:new Date()}});await audit(admin.id,req,AuditAction.UPDATE,"project_release",release.id,undefined,release);return res.json({success:true,data:release});}catch(e){return res.status(500).json({success:false,message:e instanceof Error?e.message:String(e)});} });
router.post("/releases/:id/test-complete", async(req,res)=>{try{const admin=await superAdmin(req,res);if(!admin)return;const failed=Number(req.body?.failed||0),errors=Number(req.body?.errors||0),passed=Number(req.body?.passed||0);const status=(failed||errors)?"FAILED":"PASSED";const release=await prisma.projectRelease.update({where:{id:req.params.id},data:{status,testCompletedAt:new Date(),notes:req.body?.notes?String(req.body.notes):undefined}});await prisma.testRun.create({data:{releaseId:release.id,testerMobile:req.body?.testerMobile?String(req.body.testerMobile):null,name:String(req.body?.name||"Super Admin Verification"),status,passed,failed,errors,completedAt:new Date(),results:req.body?.results as any}});await audit(admin.id,req,AuditAction.UPDATE,"project_release",release.id,undefined,{release,status});return res.json({success:true,data:{release,status}});}catch(e){return res.status(500).json({success:false,message:e instanceof Error?e.message:String(e)});} });
router.post("/releases/:id/approve", async(req,res)=>{try{const admin=await superAdmin(req,res);if(!admin)return;const release=await prisma.projectRelease.findUnique({where:{id:req.params.id}});if(!release)return res.status(404).json({success:false,message:"Release not found"});if(release.status!=="PASSED")return res.status(409).json({success:false,message:"Release must pass testing before approval"});const updated=await prisma.projectRelease.update({where:{id:release.id},data:{status:"APPROVED",approvedAt:new Date(),approvedByAdminId:admin.id}});await audit(admin.id,req,AuditAction.APPROVE,"project_release",updated.id,release,updated);return res.json({success:true,data:updated});}catch(e){return res.status(500).json({success:false,message:e instanceof Error?e.message:String(e)});} });
router.post("/releases/:id/promote", async(req,res)=>{try{const admin=await superAdmin(req,res);if(!admin)return;const release=await prisma.projectRelease.findUnique({where:{id:req.params.id}});if(!release)return res.status(404).json({success:false,message:"Release not found"});if(release.status!=="APPROVED")return res.status(409).json({success:false,message:"Only APPROVED release can be promoted"});if(String(req.body?.confirmation||"")!=="PROMOTE TO LIVE")return res.status(400).json({success:false,message:'confirmation "PROMOTE TO LIVE" required'});const updated=await prisma.projectRelease.update({where:{id:release.id},data:{status:"DEPLOYING",environment:"LIVE",deployedAt:new Date()}});const control=await ensureEnvironmentControl();const live=await prisma.environmentControl.update({where:{id:control.id},data:{activeEnvironment:"LIVE",currentVersion:updated.version,approvedVersion:updated.version,deploymentStatus:"LIVE",updatedByAdminId:admin.id}});await audit(admin.id,req,AuditAction.CONFIG_CHANGE,"production_release",updated.id,release,{updated,live});return res.json({success:true,data:{release:updated,environment:live}});}catch(e){return res.status(500).json({success:false,message:e instanceof Error?e.message:String(e)});} });

router.get("/city-zones", async(req,res)=>{try{const admin=await superAdmin(req,res);if(!admin)return;return res.json({success:true,data:await prisma.cityZone.findMany({orderBy:{city:"asc"}})});}catch(e){return res.status(500).json({success:false,message:e instanceof Error?e.message:String(e)});}});
router.post("/city-zones", async(req,res)=>{try{const admin=await superAdmin(req,res);if(!admin)return;const data={name:String(req.body?.name||"").trim(),city:String(req.body?.city||"").trim(),centerLat:Number(req.body?.centerLat),centerLng:Number(req.body?.centerLng),radiusKm:Number(req.body?.radiusKm),active:req.body?.active!==false,connectionPoint:req.body?.connectionPoint!==false,metadata:req.body?.metadata as any};if(!data.name||!data.city||!Number.isFinite(data.centerLat)||!Number.isFinite(data.centerLng)||!(data.radiusKm>0))return res.status(400).json({success:false,message:"name, city, center coordinates and positive radiusKm are required"});const zone=await prisma.cityZone.create({data});await audit(admin.id,req,AuditAction.CREATE,"city_zone",zone.id,undefined,zone);return res.json({success:true,data:zone});}catch(e){return res.status(500).json({success:false,message:e instanceof Error?e.message:String(e)});}});
router.patch("/city-zones/:id", async(req,res)=>{try{const admin=await superAdmin(req,res);if(!admin)return;const before=await prisma.cityZone.findUnique({where:{id:req.params.id}});if(!before)return res.status(404).json({success:false,message:"Zone not found"});const zone=await prisma.cityZone.update({where:{id:before.id},data:{name:req.body?.name!==undefined?String(req.body.name):undefined,city:req.body?.city!==undefined?String(req.body.city):undefined,radiusKm:req.body?.radiusKm!==undefined?Number(req.body.radiusKm):undefined,centerLat:req.body?.centerLat!==undefined?Number(req.body.centerLat):undefined,centerLng:req.body?.centerLng!==undefined?Number(req.body.centerLng):undefined,active:req.body?.active!==undefined?Boolean(req.body.active):undefined,connectionPoint:req.body?.connectionPoint!==undefined?Boolean(req.body.connectionPoint):undefined,metadata:req.body?.metadata as any}});await audit(admin.id,req,AuditAction.UPDATE,"city_zone",zone.id,before,zone);return res.json({success:true,data:zone});}catch(e){return res.status(500).json({success:false,message:e instanceof Error?e.message:String(e)});}});

router.get("/pricing-rules", async(req,res)=>{try{const admin=await superAdmin(req,res);if(!admin)return;return res.json({success:true,data:await prisma.pricingRule.findMany({orderBy:[{priority:"desc"},{createdAt:"desc"}]})});}catch(e){return res.status(500).json({success:false,message:e instanceof Error?e.message:String(e)});}});
router.post("/pricing-rules", async(req,res)=>{try{const admin=await superAdmin(req,res);if(!admin)return;const data={name:String(req.body?.name||"").trim(),active:req.body?.active!==false,serviceType:req.body?.serviceType?String(req.body.serviceType):null,bookingType:req.body?.bookingType||null,rideType:req.body?.rideType||null,vehicleType:req.body?.vehicleType||null,zoneId:req.body?.zoneId||null,minFare:req.body?.minFare!==undefined?Number(req.body.minFare):null,maxFare:req.body?.maxFare!==undefined?Number(req.body.maxFare):null,baseFare:req.body?.baseFare!==undefined?Number(req.body.baseFare):null,perKm:req.body?.perKm!==undefined?Number(req.body.perKm):null,perMinute:req.body?.perMinute!==undefined?Number(req.body.perMinute):null,waitingPerMinute:req.body?.waitingPerMinute!==undefined?Number(req.body.waitingPerMinute):null,weightPerKg:req.body?.weightPerKg!==undefined?Number(req.body.weightPerKg):null,multiplier:req.body?.multiplier!==undefined?Number(req.body.multiplier):1,priority:req.body?.priority!==undefined?Number(req.body.priority):0,dayOfWeek:req.body?.dayOfWeek?String(req.body.dayOfWeek):null,startTime:req.body?.startTime?String(req.body.startTime):null,endTime:req.body?.endTime?String(req.body.endTime):null,demandMin:req.body?.demandMin!==undefined?Number(req.body.demandMin):null,demandMax:req.body?.demandMax!==undefined?Number(req.body.demandMax):null,metadata:req.body?.metadata as any};if(!data.name)return res.status(400).json({success:false,message:"name is required"});const rule=await prisma.pricingRule.create({data:data as any});await audit(admin.id,req,AuditAction.CREATE,"pricing_rule",rule.id,undefined,rule);return res.json({success:true,data:rule});}catch(e){return res.status(500).json({success:false,message:e instanceof Error?e.message:String(e)});}});
router.patch("/pricing-rules/:id", async(req,res)=>{try{const admin=await superAdmin(req,res);if(!admin)return;const before=await prisma.pricingRule.findUnique({where:{id:req.params.id}});if(!before)return res.status(404).json({success:false,message:"Pricing rule not found"});const fields=["name","serviceType","bookingType","rideType","vehicleType","zoneId","dayOfWeek","startTime","endTime","demandMin","demandMax","minFare","maxFare","baseFare","perKm","perMinute","waitingPerMinute","weightPerKg","multiplier","priority","active","metadata"];const data:any={};for(const k of fields)if(req.body?.[k]!==undefined)data[k]=req.body[k];for(const k of ["demandMin","demandMax","priority"])if(data[k]!==undefined)data[k]=Number(data[k]);for(const k of ["minFare","maxFare","baseFare","perKm","perMinute","waitingPerMinute","weightPerKg","multiplier"])if(data[k]!==undefined)data[k]=Number(data[k]);const rule=await prisma.pricingRule.update({where:{id:before.id},data});await audit(admin.id,req,AuditAction.UPDATE,"pricing_rule",rule.id,before,rule);return res.json({success:true,data:rule});}catch(e){return res.status(500).json({success:false,message:e instanceof Error?e.message:String(e)});}});

router.get("/test-runs", async(req,res)=>{try{const admin=await superAdmin(req,res);if(!admin)return;return res.json({success:true,data:await prisma.testRun.findMany({orderBy:{startedAt:"desc"},take:100})});}catch(e){return res.status(500).json({success:false,message:e instanceof Error?e.message:String(e)});}});
router.post("/data-merge", async(req,res)=>{try{const admin=await superAdmin(req,res);if(!admin)return;const name=String(req.body?.name||"Manual data merge").trim();const job=await prisma.dataMergeJob.create({data:{name,sourceScope:String(req.body?.sourceScope||"HISTORICAL_CURRENT"),sourceQuery:req.body?.sourceQuery as any,derivativeData:req.body?.derivativeData as any,status:"DRAFT",reviewed:false}});await audit(admin.id,req,AuditAction.CREATE,"data_merge",job.id,undefined,job);return res.status(201).json({success:true,data:job});}catch(e){return res.status(500).json({success:false,message:e instanceof Error?e.message:String(e)});}});
router.patch("/data-merge/:id/review", async(req,res)=>{try{const admin=await superAdmin(req,res);if(!admin)return;const before=await prisma.dataMergeJob.findUnique({where:{id:req.params.id}});if(!before)return res.status(404).json({success:false,message:"Merge job not found"});const approved=Boolean(req.body?.approved);const job=await prisma.dataMergeJob.update({where:{id:before.id},data:{reviewed:approved,reviewedBy:admin.id,status:approved?"REVIEWED":"REJECTED"}});await audit(admin.id,req,AuditAction.UPDATE,"data_merge",job.id,before,job);return res.json({success:true,data:job});}catch(e){return res.status(500).json({success:false,message:e instanceof Error?e.message:String(e)});}});

export { router as platformRouter };
